; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
G28 ; home
G30 P0 X0 Y-120 Z-99999 ; probe near a leadscrew, half way along Y axis
G30 P1 X0 Y120 Z-99999 S2 ; probe near a leadscrew and calibrate 2 motors
G28 Z
G29  ; probe the bed and enable compensation

