; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
G91               ; relative positioning
G1 H2 Z5 F2000    ; drop Z relative to current position
G1 H1 X-300 F4000 ; coarse home X
G1 X5 F600     ; move 5mm away from the homing switch
G1 H1 X-10        ; fine home X
G1 H2 Z-5 F200    ; return Z to first state
G90               ; absolute positioning