; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
G91               ; relative positioning
G1 H2 Z5 F2000    ; drop Z relative to current position
G1 H1 Y270 F4000  ; coarse home Y
G1 Y-5 F600     	  ; move 5mm away from the homing switch
G1 H1 Y10         ; fine home Y
G1 H2 Z-5 F200    ; return Z to first state
G90               ; absolute positioning