; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
M83                   ; relative extruder moves
G1 E-5 F3600          ; retract 5mm of filament
G91                   ; relative positioning
G1 Z5 F360            ; lift Z by 5mm
G90                   ; absolute positioning
G1 H2 X-130 U140 F6000 ; park both heads
