; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
G1 R1 X0 U0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 U0          ; go back to the last print move
M83                  ; relative extruder moves
G1 E5 F3600          ; extrude 5mm of filament