; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
M83 			  ; relative extruder movement
G1 E-4 F3600 	  ; retract 4mm
M106 S0           ; turn off our print cooling fan
G91               ; relative axis movement
G1 Z3 F500        ; up 3mm
G90               ; absolute axis movement
G1 X-175 F6000 ; park the X carriage at -175mm