; tpost2.g
; called after tool 2 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Oct 30 2020 10:16:50 GMT+0000 (Greenwich Mean Time)
M106 R2           ; restore print cooling fan speed
M116 P2           ; wait for tool 2 heaters to reach operating temperature
M83               ; relative extruder movement
G1 E5 F3600 	  ; extrude 5mm
;M567 P2 E1:1      ; set tool mix ratio
;M568 P2 S1        ; turn on mixing